### ISSUE TITLE
Can you please add an env.example?

### ISSUE THREAD

**Issue by greendesertsnow** [ManuelDeLeon/sveltekit-firebase-ssr#6]
Hey there,
I keep getting this error when I follow the readme instructions. Can you please add an env.example?
`Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.getSession (C:/Users/pazar/projects/ls-sk/src/hooks.ts:11:35)
    at render_page (file:///C:/Users/pazar/projects/ls-sk/.svelte-kit/runtime/server/index.js:3000:39)
    at resolve (file:///C:/Users/pazar/projects/ls-sk/.svelte-kit/runtime/server/index.js:3309:17)
    at Object.handle (C:/Users/pazar/projects/ls-sk/src/hooks.ts:34:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (file:///C:/Users/pazar/projects/ls-sk/.svelte-kit/runtime/server/index.js:3253:20)
    at async file:///C:/Users/pazar/projects/ls-sk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.326_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/index.js:294:24
`

**Comment by ManuelDeLeon** [comment]
The readme has examples of the config objects but you should use the objects from your Firebase console and run JSON.stringify on them.
